name: C++ CI for hello world

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: install i386
        run: sudo apt-get install libc6-dev:i386 libx11-dev:i386 libxext-dev:i386 lib32gcc-7-dev
      - name: install gcc_multilib
        run: sudo apt-get install gcc-multilib g++-multilib
      - name: make
        run: make
      - name: make test
        run: make test
      - name: clean
        run: make clean