name: C++ CI for hello world

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: install gcc_multilib
        run: apt-get install gcc-multilib g++-multilib
      - name: make
        run: make
      - name: make test
        run: make test
      - name: clean
        run: make clean