name: C++ CI for hello world

on:
  push:
    branches: [main]  # limit to main branch

jobs:
  build-and-test-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install cppunit
        run: sudo apt install -y libcppunit-dev
      - name: install gcc_multilib
        run: sudo apt install build-essential gcc-multilib libx11-dev libx11-dev:i386 glslang-tools spirv-tools g++-multilib
      - name: make
        run: make
      - name: make test
        run: make test
      - name: clean
        run: make clean